version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Optional: Custom Nginx config
    restart: unless-stopped
